version: "4.0"

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=zetch
      - POSTGRES_PASSWORD=secret

  api:
    image: 'zetch-api:latest'
    build:
      context: .
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/zetch
      - SPRING_DATASOURCE_USERNAME=zetch
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



