name: ZETCH Build

env:
  API_SERVER_PROJECT: api_server

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: ./${{ env.API_SERVER_PROJECT }}
        run: ./mvnw clean install
